Remove parameters to certCache.RenewManagedCertificates
This fixes the following build error due to a signature change in the `certCache.RenewManagedCertificates` method.

```
/go/pkg/mod/github.com/pieterlouw/caddy-net@v0.1.5/caddynet/netserver/tls.go:77:48: too many arguments in call to certCache.RenewManagedCertificates
	have (bool)
	want ()
```